language: node_js
node_js:
- 5.7.0
script:
- npm test
deploy:
  provider: heroku
  app: gfw-geostore-api
  api_key:
    secure: DMKd6C1shaR84PoVl0HKxOzBxqfG3CVnj3d+OaipB8r257xSWc9XjaNNXxVp3sOKRTu4QMawOIWGlH5sOJWRZ8Dk66/HjjiAhy9Yoj8zlr7VTxZMWsl2i7mtC9Yx+ZOrpJ3lnPa7oeDwCYrgX2tHtg9GCAPishUdZsgJL8M1R2W3fhfDJFGCxEKA2MZ1QcuBYD+1SYgldJsLR9OMlV+3/BNF0FB1mm3I6a57kfg/AkJWKNkQ1dJ+SptFv9KX6dId0h9bzPpl5wrR1SIaKNrGWdkwgn6GcQwVE5VzMNBZ5gFuhHBf4ZsdyBmG5VdIUZPea996JhEcoCb2NEHGqlcvTEs/J5dIIOGEXZOOmePQOmmV0uNzRlfGfavdxGTzd4QJACNmBOPuV79Zw/z4VQa8bQ2S4mOmMukwAKyK1pSaME4snZa31qN9qw6WkaZwdUA5kRCF66iLCft/RRMgqiiTL8T3MeEqvrwzToFEIJ3USwRTWVpZLHU+quFfZWM4zzZy8hVVCWQSksRaKHmmEo1tcWpknwvZrTLK/3Mu9IjW+oLSztWeMZTUn/Av5wNeiDVsTmwGHiCyGBCYONIEr3LpK0cIw29TUDYF7A8t0mPpWovGxNsj0ByrSZ2qwpZKbeLSqSi76/jnNby83/VkMQ5CY313r2vKee+5r9xUIIhTzFE=
