version: '3'
services:
  prod:
    image: vizzuality/gfw-geostore-api:1.4.0${STAGING}-sdg
    ports:
      - "3100"
    env_file:
      - prod.env
    command: start
    logging:
      driver: "syslog"
      options:
        syslog-address: ${SYSLOG_ADDRESS}
        tag: dataset${STAGING}
